from __future__ import annotations

import hashlib
from dataclasses import asdict
from pathlib import Path
from typing import Protocol

from .config_schema import PipelineConfig
from .data_manifest import VlmSample, write_jsonl


class TeacherBackend(Protocol):
    def answer(self, sample: VlmSample) -> dict:
        ...


class MockTeacher:
    def answer(self, sample: VlmSample) -> dict:
        seed = f"{sample.id}:{sample.question}:{sample.answer or ''}"
        digest = hashlib.sha256(seed.encode("utf-8")).hexdigest()
        confidence = 0.55 + (int(digest[:4], 16) / 0xFFFF) * 0.4
        teacher_answer = sample.answer or f"mock answer for {sample.task}"
        return {
            "teacher_answer": teacher_answer,
            "teacher_confidence": round(confidence, 4),
            "teacher_rationale": "Mock backend used for pipeline validation.",
        }


class HuggingFaceTeacher:
    def __init__(self, config: PipelineConfig):
        self.config = config
        try:
            from transformers import AutoModelForVision2Seq, AutoProcessor
        except ImportError as exc:
            raise RuntimeError("Install transformers to use the Hugging Face teacher backend.") from exc

        self.processor = AutoProcessor.from_pretrained(config.teacher.model_name, trust_remote_code=True)
        self.model = AutoModelForVision2Seq.from_pretrained(
            config.teacher.model_name,
            device_map=config.teacher.device_map or "auto",
            trust_remote_code=True,
        )

    def answer(self, sample: VlmSample) -> dict:
        from PIL import Image

        image_path = self.config.data.image_root / sample.image
        image = Image.open(image_path).convert("RGB")
        prompt = self.config.distillation.prompt_template.format(question=sample.question)
        inputs = self.processor(images=image, text=prompt, return_tensors="pt").to(self.model.device)
        output_ids = self.model.generate(
            **inputs,
            do_sample=self.config.teacher.temperature > 0,
            temperature=self.config.teacher.temperature,
            max_new_tokens=self.config.teacher.max_new_tokens,
        )
        answer = self.processor.batch_decode(output_ids, skip_special_tokens=True)[0]
        return {
            "teacher_answer": answer.strip(),
            "teacher_confidence": 1.0,
            "teacher_rationale": "Generated by Hugging Face teacher backend.",
        }


def build_teacher(config: PipelineConfig) -> TeacherBackend:
    if config.teacher.backend == "mock":
        return MockTeacher()
    if config.teacher.backend == "hf":
        return HuggingFaceTeacher(config)
    raise ValueError(f"Unknown teacher backend: {config.teacher.backend}")


def create_distillation_dataset(config: PipelineConfig, samples: list[VlmSample]) -> Path:
    teacher = build_teacher(config)
    rows: list[dict] = []
    for sample in samples:
        label = teacher.answer(sample)
        if label["teacher_confidence"] < config.distillation.min_teacher_confidence:
            continue
        rows.append(
            {
                **asdict(sample),
                **label,
                config.distillation.target_field: label["teacher_answer"],
            }
        )
    write_jsonl(config.data.distill_path, rows)
    return config.data.distill_path
